# This is a basic workflow to help you get started with Actions

name: check_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Check My network Conection!
        run: |
          ip a
          curl -I https://www.twitter.com        
       # ping  -c 10 www.google.comip a 

      # Runs a set of commands using the runners shell
      - name: Get my public ip address
        run: |
          curl  https://httpbin.org/ip
          # 安装pnpm  # curl -fsSL https://get.pnpm.io/install.sh | sh -
   
          curl https://ip.fengzhao.pro/
          # 使用 pnpm env 命令来安装 Nodejs
          sudo apt-get -y install virt-what 
          sudo virt-what
          sudo curl -fsSL https://get.docker.com | bash -s docker
          sudo docker info

